[variables]
NIXPACKS_BUILD_CMD = "npm ci && cd shared && npm ci && npm run build && cd ../backend && npm ci && npm run build"
NIXPACKS_START_CMD = "cd backend && npm start"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "cd shared && npm ci", "cd backend && npm ci"]

[phases.build]
cmds = ["cd shared && npm run build", "cd backend && npm run build"]