# Generated by Django 5.2.3 on 2025-06-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('first_mentioned_date', models.DateField()),
                ('last_mentioned_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meetings', models.ManyToManyField(related_name='blockers', to='meetings.meeting')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('participation_score', models.IntegerField(default=0)),
                ('blocker_count', models.IntegerField(default=0)),
                ('repeated_blocker_count', models.IntegerField(default=0)),
                ('progress_stagnation_count', models.IntegerField(default=0)),
                ('key_roles_present', models.JSONField(default=list)),
                ('overall_health_score', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('red', 'Red - Needs Attention'), ('yellow', 'Yellow - Some Issues'), ('green', 'Green - Healthy')], default='yellow', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.team')),
            ],
        ),
    ]
