# Generated by Django 5.2.3 on 2025-06-26 20:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocker',
            options={'ordering': ['-last_mentioned_date', '-severity', '-created_at'], 'verbose_name': 'Blocker', 'verbose_name_plural': 'Blockers'},
        ),
        migrations.AlterModelOptions(
            name='teamhealthmetrics',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Team Health Metrics', 'verbose_name_plural': 'Team Health Metrics'},
        ),
        migrations.AddField(
            model_name='blocker',
            name='ai_confidence',
            field=models.FloatField(default=0.0, help_text='AI confidence in blocker detection (0-1)'),
        ),
        migrations.AddField(
            model_name='blocker',
            name='blocking_dependency',
            field=models.CharField(blank=True, help_text="What they're waiting for", max_length=200),
        ),
        migrations.AddField(
            model_name='blocker',
            name='blocking_person',
            field=models.CharField(blank=True, help_text='Person who mentioned being blocked', max_length=100),
        ),
        migrations.AddField(
            model_name='blocker',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='teamhealthmetrics',
            name='ai_analysis_raw',
            field=models.JSONField(default=dict, help_text='Raw OpenAI analysis results'),
        ),
        migrations.AddField(
            model_name='teamhealthmetrics',
            name='scrum_master_alerts',
            field=models.JSONField(default=list, help_text='Actionable items for scrum master'),
        ),
        migrations.AddField(
            model_name='teamhealthmetrics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blocker',
            name='description',
            field=models.TextField(help_text='Description of the blocker'),
        ),
        migrations.AlterField(
            model_name='blocker',
            name='first_mentioned_date',
            field=models.DateField(help_text='First time this blocker was mentioned'),
        ),
        migrations.AlterField(
            model_name='blocker',
            name='last_mentioned_date',
            field=models.DateField(help_text='Most recent mention of this blocker'),
        ),
        migrations.AlterField(
            model_name='blocker',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='blockers', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='blocker',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='dashboard.team'),
        ),
        migrations.AlterField(
            model_name='teamhealthmetrics',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='teamhealthmetrics',
            name='key_roles_present',
            field=models.JSONField(default=list, help_text='List of key roles detected: scrum_master, product_owner, etc.'),
        ),
        migrations.AlterField(
            model_name='teamhealthmetrics',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='teamhealthmetrics',
            name='overall_health_score',
            field=models.IntegerField(default=0, help_text='0-100 combined health score'),
        ),
        migrations.AlterField(
            model_name='teamhealthmetrics',
            name='participation_score',
            field=models.IntegerField(default=0, help_text='0-100 based on speaker variety and engagement'),
        ),
        migrations.AlterField(
            model_name='teamhealthmetrics',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='dashboard.team'),
        ),
        migrations.AddIndex(
            model_name='blocker',
            index=models.Index(fields=['team', 'status'], name='analytics_b_team_id_940d55_idx'),
        ),
        migrations.AddIndex(
            model_name='blocker',
            index=models.Index(fields=['first_mentioned_date'], name='analytics_b_first_m_8d5240_idx'),
        ),
        migrations.AddIndex(
            model_name='blocker',
            index=models.Index(fields=['last_mentioned_date'], name='analytics_b_last_me_8821a4_idx'),
        ),
        migrations.AddIndex(
            model_name='teamhealthmetrics',
            index=models.Index(fields=['team', 'date'], name='analytics_t_team_id_394c46_idx'),
        ),
        migrations.AddIndex(
            model_name='teamhealthmetrics',
            index=models.Index(fields=['health_status'], name='analytics_t_health__880655_idx'),
        ),
        migrations.AddIndex(
            model_name='teamhealthmetrics',
            index=models.Index(fields=['overall_health_score'], name='analytics_t_overall_136bd6_idx'),
        ),
    ]
