# Generated by Django 5.2.3 on 2025-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_blocker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
