# Generated by Django 5.2.3 on 2025-06-26 18:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('meeting_type', models.CharField(choices=[('standup', 'Standup'), ('retrospective', 'Retrospective'), ('sprint_planning', 'Sprint Planning'), ('review', 'Sprint Review'), ('other', 'Other')], default='standup', max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='meetings_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a'])])),
                ('transcription_document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('transcription_raw', models.JSONField(blank=True, null=True)),
                ('transcription_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='dashboard.team')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date'],
            },
        ),
    ]
